<?php

function getCmsPageDefaults()
{
    return [
        'index' => [
            'label' => 'Home',
            'title' => 'Welcome - Nurturing Brilliance, Shaping Futures',
            'data' => [
                'hero_badge' => 'CBSE Affiliated School - Est. 2005',
                'hero_title' => 'Where Young Minds Learn, Grow & Lead',
                'hero_description' => "SIBA Public School provides a holistic, world-class education that shapes both intellectual excellence and personal character. Join 5,000+ families who trust us with their children's future.",
                'hero_primary_cta_text' => 'Apply for Admission',
                'hero_primary_cta_link' => 'parent/register.php',
                'hero_secondary_cta_text' => 'Virtual Tour',
                'hero_secondary_cta_link' => 'about.php#virtual-tour',
                'hero_stats' => [
                    ['number' => '5000+', 'label' => 'Students Enrolled'],
                    ['number' => '150+', 'label' => 'Expert Faculty'],
                    ['number' => '98%', 'label' => 'Board Pass Rate'],
                    ['number' => '20+', 'label' => 'Years of Excellence'],
                ],
                'stats_bar' => [
                    ['number' => '45+', 'label' => 'Clubs & Activities'],
                    ['number' => '12', 'label' => 'Acres Campus'],
                    ['number' => '100%', 'label' => 'Scholarship Recipients'],
                    ['number' => '#1', 'label' => 'Rated in the District'],
                ],
                'about_badge' => 'About SIBA',
                'about_heading' => 'A Legacy of Academic Excellence',
                'about_text' => 'For over two decades, SIBA Public School has been shaping future leaders with a curriculum that balances academic rigour, creative thinking, and strong values.',
                'about_image' => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&q=80&w=800',
                'about_points' => [
                    ['icon' => 'book', 'title' => 'CBSE Curriculum', 'text' => 'Nationally recognized board-aligned curriculum with a focus on conceptual clarity and application-based learning.'],
                    ['icon' => 'heart', 'title' => 'Value-Based Education', 'text' => 'We mould not just scholars but responsible citizens through a disciplined and ethical environment.'],
                    ['icon' => 'globe', 'title' => 'Global Exposure', 'text' => 'International exchange programs, MUN, and technology integrations that prepare students for a global future.'],
                ],
                'offerings_badge' => 'Our Offerings',
                'offerings_heading' => 'Everything Your Child Needs to Succeed',
                'offerings_text' => "A complete ecosystem built to nurture every dimension of a student's development.",
                'offerings' => [
                    ['icon' => 'flask', 'title' => 'Science & Labs', 'text' => 'State-of-the-art Physics, Chemistry, and Biology labs equipped with modern instruments for hands-on learning.'],
                    ['icon' => 'desktop', 'title' => 'Digital Learning', 'text' => 'Smart classrooms with interactive boards, 1:1 device program, and high-speed campus-wide Wi-Fi.'],
                    ['icon' => 'running', 'title' => 'Sports & Fitness', 'text' => 'Football, cricket, basketball, swimming, and athletics coached by state-level sports professionals.'],
                    ['icon' => 'palette', 'title' => 'Arts & Culture', 'text' => 'Music, dance, drama, painting, and photography studios that nurture creative expression in every child.'],
                    ['icon' => 'book-open', 'title' => 'Library & Research', 'text' => 'A vast collection of books, e-journals, and a dedicated research room for senior students.'],
                    ['icon' => 'bus', 'title' => 'Safe Transport', 'text' => 'GPS-enabled buses covering major routes with trained drivers and attendants for safe journeys.'],
                ],
                'admission_badge' => 'Admissions 2026-27',
                'admission_heading' => 'Simple 4-Step Admission Process',
                'admission_text' => "Joining SIBA is easy. Here's how you get your child started on a remarkable journey.",
                'admission_steps' => [
                    ['title' => 'Register Online', 'text' => 'Create your Parent Portal account with phone number verification.'],
                    ['title' => 'Fill Application', 'text' => "Complete the child's details form and upload required documents."],
                    ['title' => 'Assessment', 'text' => 'Attend a scheduled interview or entrance assessment as notified.'],
                    ['title' => 'Enrolment', 'text' => 'Receive admission confirmation and pay fees through the portal.'],
                ],
                'admission_cta_primary_text' => 'Start Your Application',
                'admission_cta_primary_link' => 'parent/register.php',
                'admission_cta_secondary_text' => 'Learn More',
                'admission_cta_secondary_link' => 'admissions.php',
                'events_badge' => "What's Happening",
                'events_heading' => 'Upcoming Events & Notices',
                'events' => [
                    ['day' => '15', 'month' => 'Apr', 'title' => 'Annual Athletic Meet 2026', 'text' => 'All parents are invited. Registration mandatory at the school office.'],
                    ['day' => '22', 'month' => 'Apr', 'title' => 'Class 10 & 12 Result Declaration', 'text' => 'Board results will be displayed on the school notice board by 10 AM.'],
                    ['day' => '01', 'month' => 'May', 'title' => 'Admissions Open - New Batch Orientation', 'text' => 'Newly admitted students and parents are invited for the welcome session.'],
                    ['day' => '05', 'month' => 'May', 'title' => 'Science Exhibition & Fair', 'text' => 'Students from Grade 6-12 showcase innovative science projects.'],
                ],
                'testimonials_badge' => 'Parent Voices',
                'testimonials_heading' => 'What Parents Say',
                'testimonials' => [
                    ['text' => 'SIBA has transformed my daughter completely. The teachers are supportive and the environment is truly nurturing.', 'name' => 'Priya Sharma', 'role' => 'Mother of Class 8 student', 'image' => 'https://images.unsplash.com/photo-1494790108755-2616b612b8e0?auto=format&fit=crop&q=80&w=100'],
                    ['text' => 'The online admission process was seamless. The Parent Portal kept us updated at every step.', 'name' => 'Rahul Gupta', 'role' => 'Father of Class 5 student', 'image' => 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=100'],
                ],
                'final_cta_heading' => 'Ready to Give Your Child the Best Start?',
                'final_cta_text' => "Admissions are now open. Seats are limited - secure your child's future today.",
                'final_cta_primary_text' => 'Apply for Admission',
                'final_cta_primary_link' => 'parent/register.php',
                'final_cta_secondary_text' => 'Contact Us',
                'final_cta_secondary_link' => 'contact.php',
                'contact_strip' => [
                    ['icon' => 'phone-alt', 'label' => 'Call Us', 'value' => '+91 12345 67890'],
                    ['icon' => 'envelope', 'label' => 'Email Us', 'value' => 'info@sibaschool.com'],
                    ['icon' => 'map-marker-alt', 'label' => 'Visit Us', 'value' => '123 Education Lane, City'],
                    ['icon' => 'clock', 'label' => 'School Hours', 'value' => 'Mon-Fri: 8 AM - 3 PM'],
                ],
            ],
        ],
        'about' => [
            'label' => 'About',
            'title' => 'About Us',
            'data' => [
                'hero_title' => 'About SIBA Public School',
                'hero_text' => 'A legacy of excellence, values, and academic achievement since 2005.',
                'foundation_badge' => 'Our Foundation',
                'foundation_heading' => 'Vision & Mission',
                'foundation_cards' => [
                    ['icon' => 'eye', 'title' => 'Our Vision', 'text' => 'To be a leading educational institution that nurtures lifelong learners, responsible citizens, and compassionate global leaders.'],
                    ['icon' => 'bullseye', 'title' => 'Our Mission', 'text' => 'To provide a holistic, inclusive, and inspiring environment where every student can discover their potential.'],
                    ['icon' => 'star', 'title' => 'Our Values', 'text' => 'Integrity, Excellence, Respect, and Compassion guide everything we do.'],
                ],
                'story_badge' => 'Our Story',
                'story_heading' => 'Two Decades of Shaping Futures',
                'story_image' => 'https://images.unsplash.com/photo-1523050854058-8df90110c9f1?auto=format&fit=crop&q=80&w=800',
                'story_paragraphs' => [
                    'Founded in 2005 with just 120 students and a handful of dedicated educators, SIBA Public School was born from a simple belief: every child deserves world-class education.',
                    'Over the past two decades, we have grown into one of the region\'s respected institutions with 5,000+ students and 150+ faculty members.',
                    'Our alumni have gone on to lead in medicine, engineering, business, arts, and public service.',
                ],
                'story_stats' => [
                    ['number' => '2005', 'label' => 'Year Founded'],
                    ['number' => '5000+', 'label' => 'Students'],
                    ['number' => '150+', 'label' => 'Faculty'],
                    ['number' => '98%', 'label' => 'Pass Rate'],
                ],
                'leadership_badge' => 'Our People',
                'leadership_heading' => 'Leadership Team',
                'leadership_text' => "Guided by experienced educators and visionary leaders committed to every child's success.",
                'leaders' => [
                    ['name' => 'Dr. Sarah Williams', 'role' => 'Principal', 'bio' => 'Ph.D in Education. 25+ years in academic leadership and school administration.', 'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200'],
                    ['name' => 'Mr. James Carter', 'role' => 'Vice Principal', 'bio' => 'M.Ed., specialising in curriculum design and teacher development programs.', 'image' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200'],
                    ['name' => 'Ms. Priya Menon', 'role' => 'Head of Science', 'bio' => 'M.Sc., Physics. Transforming science education with inquiry-based learning.', 'image' => 'https://images.unsplash.com/photo-1494790108755-2616b612b8e0?auto=format&fit=crop&q=80&w=200'],
                ],
                'cta_heading' => 'Want to Be Part of Our Story?',
                'cta_text' => 'Admissions are open for the 2026-27 academic year. Apply today.',
                'cta_primary_text' => 'Apply Now',
                'cta_primary_link' => 'parent/register.php',
                'cta_secondary_text' => 'Contact Us',
                'cta_secondary_link' => 'contact.php',
            ],
        ],
        'academics' => [
            'label' => 'Academics',
            'title' => 'Academics',
            'data' => [
                'hero_title' => 'Academics at SIBA',
                'hero_text' => 'A rigorous, balanced curriculum that prepares students for lifelong success.',
                'curriculum_badge' => 'Curriculum',
                'curriculum_heading' => 'CBSE-Aligned, Future-Ready Learning',
                'curriculum_image' => 'https://images.unsplash.com/photo-1427504494785-3a9ca7044f45?auto=format&fit=crop&q=80&w=800',
                'curriculum_points' => [
                    ['icon' => 'book', 'title' => 'Foundational Years (Class 1-5)', 'text' => 'Building literacy, numeracy and curiosity through activity-based learning methods.'],
                    ['icon' => 'brain', 'title' => 'Middle School (Class 6-8)', 'text' => 'Developing analytical and problem-solving skills across core subjects.'],
                    ['icon' => 'graduation-cap', 'title' => 'Senior School (Class 9-12)', 'text' => 'Board-focused preparation with stream specialisation and career guidance.'],
                ],
                'streams_badge' => 'Streams & Departments',
                'streams_heading' => 'Choose Your Academic Path',
                'streams_text' => 'We offer three distinct streams for Classes 11 and 12 with dedicated faculty.',
                'streams' => [
                    ['icon' => 'flask', 'title' => 'Science Stream', 'text' => 'PCM and PCB combinations with strong preparation for IIT-JEE, NEET, and other exams.'],
                    ['icon' => 'chart-bar', 'title' => 'Commerce Stream', 'text' => 'Accountancy, Business Studies, Economics, and applied math options.'],
                    ['icon' => 'landmark', 'title' => 'Humanities Stream', 'text' => 'History, Political Science, Geography, Sociology, Psychology, and Fine Arts.'],
                ],
                'cocurricular_badge' => 'Beyond the Classroom',
                'cocurricular_heading' => 'Co-Curricular Activities',
                'cocurricular_text' => 'Our programs develop well-rounded individuals beyond academics.',
                'cocurricular' => [
                    ['icon' => 'futbol', 'title' => 'Sports', 'text' => 'Football, cricket, basketball, swimming, and athletics.'],
                    ['icon' => 'paint-brush', 'title' => 'Visual Arts', 'text' => 'Painting, sculpture, photography, and digital art.'],
                    ['icon' => 'music', 'title' => 'Performing Arts', 'text' => 'Dance, drama, music, and debate events year-round.'],
                    ['icon' => 'robot', 'title' => 'STEM Clubs', 'text' => 'Robotics, coding, olympiad prep, and science fair teams.'],
                ],
                'cta_heading' => 'Ready to Join Our Academic Community?',
                'cta_text' => "Apply today and secure your child's path to excellence.",
                'cta_text_button' => 'Apply for Admission',
                'cta_link' => 'parent/register.php',
            ],
        ],
        'admissions' => [
            'label' => 'Admissions',
            'title' => 'Admissions',
            'data' => [
                'hero_title' => 'Admissions 2026-27',
                'hero_text' => "Seats are limited. Start your child's SIBA journey today.",
                'steps_badge' => 'How to Apply',
                'steps_heading' => 'Simple 4-Step Admission Process',
                'steps' => [
                    ['title' => 'Register Online', 'text' => 'Create your Parent Portal account with a valid phone number.'],
                    ['title' => 'Fill Application', 'text' => "Complete the child's profile and upload required documents."],
                    ['title' => 'Interview / Test', 'text' => 'Our team reviews the application and schedules an assessment.'],
                    ['title' => 'Enrolment', 'text' => 'Receive admission confirmation and complete enrolment online.'],
                ],
                'steps_cta_text' => 'Start Application Now',
                'steps_cta_link' => 'parent/register.php',
                'eligibility_heading' => 'Eligibility Criteria',
                'eligibility_items' => [
                    ['key' => 'Class 1', 'value' => 'Age 5-6 years as of 1st April'],
                    ['key' => 'Class 2-8', 'value' => 'Promoted from previous class with passing marks'],
                    ['key' => 'Class 9', 'value' => 'Class 8 pass certificate from a recognised school'],
                    ['key' => 'Class 11', 'value' => 'Class 10 pass with minimum 55%'],
                    ['key' => 'Documents', 'value' => 'Birth certificate, report card, and school records'],
                ],
                'fees_heading' => 'Fee Structure (Annual)',
                'fees_items' => [
                    ['key' => 'Class 1-5', 'value' => 'Rs 48,000 / year'],
                    ['key' => 'Class 6-8', 'value' => 'Rs 55,000 / year'],
                    ['key' => 'Class 9-10', 'value' => 'Rs 62,000 / year'],
                    ['key' => 'Class 11-12 (Sci)', 'value' => 'Rs 72,000 / year'],
                    ['key' => 'Class 11-12 (Com/Hum)', 'value' => 'Rs 65,000 / year'],
                ],
                'fees_note' => 'Fees may be paid quarterly. Hostel and transport charges are additional.',
                'docs_badge' => 'Documents Required',
                'docs_heading' => "What You'll Need to Upload",
                'docs' => [
                    ['icon' => 'file-alt', 'title' => 'Birth Certificate', 'text' => 'Required for all students.'],
                    ['icon' => 'id-card', 'title' => 'Aadhaar Card', 'text' => 'Optional but recommended for verification.'],
                    ['icon' => 'camera', 'title' => "Child's Photo", 'text' => 'Recent passport-size JPEG or PNG photo.'],
                    ['icon' => 'school', 'title' => 'Previous Marksheet', 'text' => 'For Class 2 and above.'],
                ],
                'faq_badge' => 'FAQ',
                'faq_heading' => 'Frequently Asked Questions',
                'faqs' => [
                    ['question' => 'When do admissions open?', 'answer' => 'Admissions open in January for the upcoming academic year.'],
                    ['question' => 'Is there an entrance test?', 'answer' => 'Yes, depending on the class and seat availability.'],
                    ['question' => 'Can I visit the school before applying?', 'answer' => 'Yes, school tours are available on working days.'],
                    ['question' => 'Is there a hostel facility?', 'answer' => 'Yes, separate hostels are available for boys and girls.'],
                    ['question' => 'Are scholarships available?', 'answer' => 'Yes, merit-based scholarships are available.'],
                ],
                'cta_heading' => 'Ready to Apply?',
                'cta_text' => "Register on the Parent Portal and start your child's admission in minutes.",
                'cta_button' => 'Apply Now',
                'cta_link' => 'parent/register.php',
            ],
        ],
        'campus-life' => [
            'label' => 'Campus Life',
            'title' => 'Campus Life',
            'data' => [
                'hero_title' => 'Life at SIBA Campus',
                'hero_text' => 'A vibrant 12-acre campus built for learning, growing, and thriving.',
                'infra_badge' => 'Infrastructure',
                'infra_heading' => 'World-Class Facilities',
                'infra_text' => 'Every space on our campus is designed to inspire and support student excellence.',
                'infrastructure' => [
                    ['icon' => 'flask', 'title' => 'Science Laboratories', 'text' => 'Modern Physics, Chemistry, Biology, and Computer labs.'],
                    ['icon' => 'book-open', 'title' => 'Central Library', 'text' => 'Extensive volumes, e-journals, and quiet reading spaces.'],
                    ['icon' => 'chalkboard-teacher', 'title' => 'Smart Classrooms', 'text' => 'Interactive classrooms with digital boards and Wi-Fi.'],
                    ['icon' => 'swimming-pool', 'title' => 'Sports Complex', 'text' => 'Pool, courts, grounds, and athletics facilities.'],
                    ['icon' => 'utensils', 'title' => 'Cafeteria & Canteen', 'text' => 'Hygienic and nutritionist-approved meals.'],
                    ['icon' => 'bus', 'title' => 'Transport', 'text' => 'GPS-tracked buses covering major routes.'],
                ],
                'hostel_badge' => 'Residential Life',
                'hostel_heading' => 'A Home Away from Home',
                'hostel_image' => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800',
                'hostel_text' => 'Our separate boys and girls hostels provide a safe, structured, and nurturing environment.',
                'hostel_points' => [
                    ['icon' => 'bed', 'title' => 'Comfortable Accommodation', 'text' => 'Spacious rooms and essential amenities.'],
                    ['icon' => 'shield-alt', 'title' => 'Safety & Security', 'text' => 'CCTV surveillance and supervised access.'],
                    ['icon' => 'heart', 'title' => 'Wellness & Health', 'text' => 'Resident nurse and medical support.'],
                ],
                'student_badge' => 'Student Experience',
                'student_heading' => 'More Than Just School',
                'student_text' => "Our campus is alive with events, clubs, and community - there's always something happening.",
                'student_life' => [
                    ['image' => 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=600', 'title' => 'Annual Day & Cultural Fest', 'text' => 'Flagship events showcasing arts and student talent.'],
                    ['image' => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=600', 'title' => 'Inter-School Sports Tournaments', 'text' => 'District and state-level achievements in multiple sports.'],
                    ['image' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600', 'title' => 'Science & Innovation Fair', 'text' => 'Original student research and innovation showcases.'],
                ],
                'cta_heading' => 'Come See It for Yourself',
                'cta_text' => 'Schedule a campus tour and experience SIBA first-hand.',
                'cta_primary_text' => 'Schedule a Tour',
                'cta_primary_link' => 'contact.php',
                'cta_secondary_text' => 'Apply Now',
                'cta_secondary_link' => 'parent/register.php',
            ],
        ],
        'events' => [
            'label' => 'Events & News',
            'title' => 'Events & News',
            'data' => [
                'hero_title' => 'Events & Latest News',
                'hero_text' => 'Stay updated with the latest happenings at SIBA Public School.',
                'events_badge' => 'Calendar',
                'events_heading' => 'Upcoming Events',
                'events' => [
                    ['day' => '15', 'month' => 'Apr', 'title' => 'Annual Athletic Meet 2026', 'text' => 'All parents and guardians are invited to attend.', 'icon' => 'running', 'color' => '#4b5563'],
                    ['day' => '22', 'month' => 'Apr', 'title' => 'Class 10 & 12 Board Results', 'text' => 'Results displayed by 10 AM with counselor support.', 'icon' => 'graduation-cap', 'color' => '#272727'],
                    ['day' => '01', 'month' => 'May', 'title' => 'New Batch Orientation Day', 'text' => 'Welcome session for newly admitted students and parents.', 'icon' => 'handshake', 'color' => '#feb630'],
                    ['day' => '05', 'month' => 'May', 'title' => 'Science & Innovation Fair 2026', 'text' => 'Students from Grades 6-12 present original projects.', 'icon' => 'flask', 'color' => '#5eabe3'],
                ],
                'news_badge' => 'News',
                'news_heading' => 'Latest from SIBA',
                'news' => [
                    ['image' => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=600', 'category' => 'Achievement', 'title' => 'SIBA Wins State Basketball Championship', 'text' => "Our U-17 boys' basketball team won the state trophy for the third year.", 'date' => 'March 20, 2026'],
                    ['image' => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&q=80&w=600', 'category' => 'Academic', 'title' => 'Students Excel in Maths Olympiad', 'text' => 'Five students qualified for the national round with medal wins.', 'date' => 'March 10, 2026'],
                    ['image' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600', 'category' => 'Infrastructure', 'title' => 'New Digital Library Wing Inaugurated', 'text' => 'Expanded digital library with e-books and research pods is now open.', 'date' => 'February 28, 2026'],
                ],
            ],
        ],
        'contact' => [
            'label' => 'Contact',
            'title' => 'Contact Us',
            'data' => [
                'hero_title' => 'Get in Touch',
                'hero_text' => "We'd love to hear from you. Reach us anytime through the channels below.",
                'details_badge' => 'Contact Details',
                'details_heading' => 'School Office',
                'contacts' => [
                    ['icon' => 'map-marker-alt', 'title' => 'Address', 'value' => '123 Education Lane, City, State - 700001, India'],
                    ['icon' => 'phone', 'title' => 'Phone', 'value' => '+91 12345 67890 (Reception)\n+91 98765 43210 (Admissions Cell)'],
                    ['icon' => 'envelope', 'title' => 'Email', 'value' => "info@sibaschool.com\nadmissions@sibaschool.com"],
                    ['icon' => 'clock', 'title' => 'Office Hours', 'value' => "Monday to Friday: 8:00 AM - 4:00 PM\nSaturday: 9:00 AM - 12:00 PM (Admissions only)"],
                ],
                'portal_title' => 'Parent Portal',
                'portal_text' => 'For admission tracking, fee payment, and updates, log in to the Parent Portal.',
                'portal_button_text' => 'Parent Login',
                'portal_button_link' => 'parent/login.php',
                'form_heading' => 'Send Us an Enquiry',
                'form_topics' => [
                    'Admission Inquiry',
                    'Fee Related',
                    'Hostel & Transport',
                    'Academic Information',
                    'Other',
                ],
                'form_footer' => 'We typically respond within 1 business day.',
                'map_title' => 'Interactive map coming soon',
                'map_subtitle' => '123 Education Lane, City, State - 700001',
            ],
        ],
    ];
}
