<?php

function getCmsPageDefaults()
{
    return [
        'index' => [
            'label' => 'Home',
            'title' => 'Welcome - Nurturing Brilliance, Shaping Futures',
            'data' => [
                'hero_badge' => 'WBBSE Affiliated School - Est. 2005',
                'hero_title' => 'Where Young Minds Learn, Grow & Lead',
                'hero_description' => "SIBA Public School provides a holistic, world-class education that shapes both intellectual excellence and personal character. Join 5,000+ families who trust us with their children's future.",
                'hero_primary_cta_text' => 'Apply for Admission',
                'hero_primary_cta_link' => 'parent/register.php',
                'hero_secondary_cta_text' => 'Virtual Tour',
                'hero_secondary_cta_link' => 'about.php#virtual-tour',
                'hero_stats' => [
                    ['number' => '5000+', 'label' => 'Students Enrolled'],
                    ['number' => '150+', 'label' => 'Expert Faculty'],
                    ['number' => '98%', 'label' => 'Board Pass Rate'],
                    ['number' => '20+', 'label' => 'Years of Excellence'],
                ],
                'stats_bar' => [
                    ['number' => '10+', 'label' => 'Best in class Faculties'],
                    ['number' => '12', 'label' => 'Acres Campus'],
                    ['number' => '100%', 'label' => 'Bengali Medium'],
                    ['number' => '#1', 'label' => 'Rated in the District'],
                ],
                'about_badge' => 'About SIBA',
                'about_heading' => 'A Legacy of Academic Excellence',
                'about_text' => 'SIBA Public School is on a journey to create future leaders with a curriculum that balances academic rigour, creative thinking, and strong values.',
                'about_image' => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&q=80&w=800',
                'about_points' => [
                    ['icon' => 'book', 'title' => 'WBBSE Curriculum', 'text' => 'State recognized board-aligned curriculum with a focus on conceptual clarity and application-based learning.'],
                    ['icon' => 'heart', 'title' => 'Value-Based Education', 'text' => 'We mould not just scholars but responsible citizens through a disciplined and ethical environment.'],
                    ['icon' => 'globe', 'title' => 'Lush green Campus', 'text' => 'A serene, eco-friendly campus with abundant greenery, open spaces, and a refreshing environment that inspires learning and well-being.'],
                ],
                'offerings_badge' => 'Our Offerings',
                'offerings_heading' => 'Everything Your Child Needs to Succeed',
                'offerings_text' => "A complete ecosystem built to nurture every dimension of a student's development.",
                'offerings' => [
                    ['icon' => 'flask', 'title' => 'Experienced & Caring Teachers', 'text' => 'Dedicated educators provide individual attention, nurturing every child\'s academic, social, and emotional growth in a supportive learning environment.'],
                    ['icon' => 'desktop', 'title' => 'Activity-Based Learning', 'text' => 'Hands-on activities, creative projects, and interactive lessons that make learning enjoyable while building confidence, curiosity, and practical skills.'],
                    ['icon' => 'running', 'title' => 'Sports & Physical Development', 'text' => 'Spacious playgrounds and indoor games encourage fitness, teamwork, discipline, and healthy habits for every child.'],
                    ['icon' => 'palette', 'title' => 'Affordable Quality Education', 'text' => 'Experienced teachers, personal attention, regular parent-teacher interaction, and affordable fees provide quality education that every family can trust.'],
                    ['icon' => 'book-open', 'title' => 'Library & Reading Corner', 'text' => 'A child-friendly library filled with storybooks, reference books, and age-appropriate learning resources that inspire a lifelong love for reading.'],
                    ['icon' => 'bus', 'title' => 'Safe & Secure Campus', 'text' => 'CCTV-monitored premises, dedicated school transport, and a well-equipped medical room ensure a safe and caring environment for every student.'],
                ],
                'admission_badge' => 'Admissions 2026-27',
                'admission_heading' => 'Simple 4-Step Admission Process',
                'admission_text' => "Joining SIBA is easy. Here's how you get your child started on a remarkable journey.",
                'admission_steps' => [
                    ['title' => 'Register Online', 'text' => 'Create your Parent Portal account with phone number verification.'],
                    ['title' => 'Fill Application', 'text' => "Complete the child's details form and upload required documents."],
                    ['title' => 'Assessment', 'text' => 'Attend a scheduled interview or entrance assessment as notified.'],
                    ['title' => 'Enrolment', 'text' => 'Receive admission confirmation and pay fees through the portal.'],
                ],
                'admission_cta_primary_text' => 'Start Your Application',
                'admission_cta_primary_link' => 'parent/register.php',
                'admission_cta_secondary_text' => 'Learn More',
                'admission_cta_secondary_link' => 'admissions.php',
                'events_badge' => "What's Happening",
                'events_heading' => 'Upcoming Events & Notices',
                'events' => [],
                'testimonials_badge' => 'Parent Voices',
                'testimonials_heading' => 'What Parents Say',
                'testimonials' => [
                    ['text' => 'SIBA has transformed my daughter completely. The teachers are supportive and the environment is truly nurturing.', 'name' => 'Bimal Bhattacharya', 'role' => 'Parent', 'image' => ''],
                    ['text' => 'The online admission process was seamless. The Parent Portal kept us updated at every step.', 'name' => 'Swapan Das', 'role' => 'Parent', 'image' => ''],
                ],
                'final_cta_heading' => 'Ready to Give Your Child the Best Start?',
                'final_cta_text' => "Admissions are now open. Seats are limited - secure your child's future today.",
                'final_cta_primary_text' => 'Apply for Admission',
                'final_cta_primary_link' => 'parent/register.php',
                'final_cta_secondary_text' => 'Contact Us',
                'final_cta_secondary_link' => 'contact.php',
                'contact_strip' => [
                    ['icon' => 'phone-alt', 'label' => 'Call Us', 'value' => '+91-75010119960'],
                    ['icon' => 'envelope', 'label' => 'Email Us', 'value' => 'info@sibapublicschool.com'],
                    ['icon' => 'map-marker-alt', 'label' => 'Visit Us', 'value' => 'Bangaljhi, West Bengal 741123'],
                    ['icon' => 'clock', 'label' => 'School Hours', 'value' => "Mon – Fri: 7 am – 3 pm\nSat: 7 am – 1 pm"],
                ],
            ],
        ],
        'about' => [
            'label' => 'About',
            'title' => 'About Us',
            'data' => [
                'hero_title' => 'About SIBA Public School',
                'hero_text' => 'A legacy of excellence, values, and academic achievement since 2005.',
                'foundation_badge' => 'Our Foundation',
                'foundation_heading' => 'Vision & Mission',
                'foundation_cards' => [
                    ['icon' => 'eye', 'title' => 'Our Vision', 'text' => 'To be a leading educational institution that nurtures lifelong learners, responsible citizens, and compassionate global leaders.'],
                    ['icon' => 'bullseye', 'title' => 'Our Mission', 'text' => 'To provide a holistic, inclusive, and inspiring environment where every student can discover their potential.'],
                    ['icon' => 'star', 'title' => 'Our Values', 'text' => 'Integrity, Excellence, Respect, and Compassion guide everything we do.'],
                ],
                'story_badge' => 'Our Story',
                'story_heading' => 'A New Beginning for Future Leaders',
                'story_image' => SITE_URL . '/assets/images/siba_banner1.jpeg',
                'story_paragraphs' => [
                    'Every great institution begins with a vision. Our mission is to create a learning environment where children feel safe, valued, and inspired to achieve their fullest potential.',
                    'With dedicated teachers, modern facilities, activity-based learning, and strong parent-school collaboration, we strive to provide an education that shapes confident, responsible, and compassionate individuals.',
                    'As we begin this journey, we invite families to become part of a school community committed to excellence, character, and lifelong learning.',
                ],
                'story_stats' => [
                    ['number' => 'Play School', 'label' => 'Starting from Early Years'],
                    ['number' => 'Class VIII', 'label' => 'Academic Programme'],
                    ['number' => 'Affordable Fees', 'label' => 'Quality Education for Every Family'],
                    ['number' => 'Safe Campus', 'label' => 'CCTV, Transport & Medical Support'],
                ],
                'leadership_badge' => 'Our People',
                'leadership_heading' => 'Leadership Team',
                'leadership_text' => "Guided by experienced educators and visionary leaders committed to every child's success.",
                'leaders' => [
                    ['name' => 'Dr. Sarah Williams', 'role' => 'Principal', 'bio' => 'Ph.D in Education. 25+ years in academic leadership and school administration.', 'image' => 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200'],
                    ['name' => 'Mr. James Carter', 'role' => 'Vice Principal', 'bio' => 'M.Ed., specialising in curriculum design and teacher development programs.', 'image' => 'https://images.unsplash.com/photo-1560250097-0b93528c311a?auto=format&fit=crop&q=80&w=200'],
                    ['name' => 'Ms. Priya Menon', 'role' => 'Head of Science', 'bio' => 'M.Sc., Physics. Transforming science education with inquiry-based learning.', 'image' => 'https://images.unsplash.com/photo-1494790108755-2616b612b8e0?auto=format&fit=crop&q=80&w=200'],
                ],
                'cta_heading' => 'Want to Be Part of Our Story?',
                'cta_text' => 'Admissions are open for the 2026-27 academic year. Apply today.',
                'cta_primary_text' => 'Admission',
                'cta_primary_link' => 'parent/register.php',
                'cta_secondary_text' => 'Contact Us',
                'cta_secondary_link' => 'contact.php',
            ],
        ],
        'academics' => [
            'label' => 'Academics',
            'title' => 'Academics',
            'data' => [
                'hero_title' => 'Academics at SIBA',
                'hero_text' => 'A rigorous, balanced curriculum that prepares students for lifelong success.',
                'curriculum_badge' => 'ACADEMIC PROGRAMME',
                'curriculum_heading' => 'Learning That Inspires Every Child',
                'curriculum_intro' => 'Our well-structured curriculum blends academic excellence with creativity, values, and practical learning. From early childhood to upper primary, we focus on developing confident, responsible, and lifelong learners through engaging and child-friendly teaching methods.',
                'curriculum_image' => SITE_URL . '/assets/images/siba_banner1.jpeg',
                'curriculum_points' => [
                    ['icon' => 'child', 'title' => 'Foundational Stage (Play School – UKG)', 'text' => 'Creating a joyful learning environment where children explore, discover, and develop essential social, emotional, and communication skills.'],
                    ['icon' => 'book', 'title' => 'Primary Stage (Class I – IV)', 'text' => 'Strengthening literacy, numeracy, and critical thinking through interactive lessons, activities, and personalized guidance.'],
                    ['icon' => 'graduation-cap', 'title' => 'Upper Primary Stage (Class V – VIII)', 'text' => 'Preparing students with strong academic foundations, problem-solving abilities, leadership qualities, and values to excel in higher education and life.'],
                ],
                'streams_badge' => 'Streams & Departments',
                'streams_heading' => 'Choose Your Academic Path',
                'streams_text' => 'We offer three distinct streams for Classes 11 and 12 with dedicated faculty.',
                'streams' => [
                    ['icon' => 'flask', 'title' => 'Science Stream', 'text' => 'PCM and PCB combinations with strong preparation for IIT-JEE, NEET, and other exams.'],
                    ['icon' => 'chart-bar', 'title' => 'Commerce Stream', 'text' => 'Accountancy, Business Studies, Economics, and applied math options.'],
                    ['icon' => 'landmark', 'title' => 'Humanities Stream', 'text' => 'History, Political Science, Geography, Sociology, Psychology, and Fine Arts.'],
                ],
                'cocurricular_badge' => 'BEYOND THE CLASSROOM',
                'cocurricular_heading' => 'Learning Beyond Books',
                'cocurricular_text' => 'We believe that every child learns best by exploring, creating, and participating. Our co-curricular activities help students build confidence, creativity, teamwork, and leadership alongside academic excellence.',
                'cocurricular' => [
                    ['icon' => 'futbol', 'title' => 'Sports & Games', 'text' => 'Children enjoy a variety of outdoor and indoor games that promote physical fitness, teamwork, discipline, and a healthy lifestyle.'],
                    ['icon' => 'paint-brush', 'title' => 'Art & Creative Expression', 'text' => 'Drawing, painting, craftwork, and creative activities encourage imagination, self-expression, and artistic development from an early age.'],
                    ['icon' => 'music', 'title' => 'Music, Dance & Cultural Activities', 'text' => 'Students participate in music, dance, drama, storytelling, and cultural celebrations that build confidence and showcase their talents.'],
                    ['icon' => 'star', 'title' => 'Clubs & Special Activities', 'text' => 'Fun learning experiences, educational competitions, quizzes, celebrations, environmental awareness programmes, and community activities help children discover new interests and develop important life skills.'],
                ],
                'cta_heading' => 'Ready to Join Our Academic Community?',
                'cta_text' => "Apply today and secure your child's path to excellence.",
                'cta_text_button' => 'Apply for Admission',
                'cta_link' => 'parent/register.php',
            ],
        ],
        'admissions' => [
            'label' => 'Admissions',
            'title' => 'Admissions',
            'data' => [
                'hero_title' => 'Admissions 2026-27',
                'hero_text' => "Seats are limited. Start your child's SIBA journey today.",
                'steps_badge' => 'How to Apply',
                'steps_heading' => 'Simple 4-Step Admission Process',
                'steps' => [
                    ['title' => 'Register Online', 'text' => 'Create your Parent Portal account with a valid phone number.'],
                    ['title' => 'Fill Application', 'text' => "Complete the child's profile and upload required documents."],
                    ['title' => 'Interview / Test', 'text' => 'Our team reviews the application and schedules an assessment.'],
                    ['title' => 'Enrolment', 'text' => 'Receive admission confirmation and complete enrolment online.'],
                ],
                'steps_cta_text' => 'Start Application Now',
                'steps_cta_link' => 'parent/register.php',
                'eligibility_heading' => 'Eligibility Criteria',
                'eligibility_items' => [
                    ['key' => 'Play School – UKG', 'value' => 'Admission based on the prescribed age criteria as of 1st April of the academic year.'],
                    ['key' => 'Class I', 'value' => 'Students should meet the minimum age requirement and have completed the previous academic level.'],
                    ['key' => 'Classes II – VIII', 'value' => 'Students must have successfully passed the previous class from a recognised school. Admission is subject to seat availability.'],
                ],
                'fees_heading' => 'Documents Required',
                'fees_items' => [
                    ['key' => 'Birth Certificate', 'value' => ''],
                    ['key' => 'Aadhaar Card', 'value' => 'Student & Parent'],
                    ['key' => 'Previous School Report Card', 'value' => 'if applicable'],
                    ['key' => 'Transfer Certificate', 'value' => 'for applicable classes'],
                    ['key' => 'Passport-size Photographs', 'value' => ''],
                ],
                'fees_note' => '',
                'docs_badge' => 'Documents Required',
                'docs_heading' => "What You'll Need to Upload",
                'docs' => [
                    ['icon' => 'file-alt', 'title' => 'Birth Certificate', 'text' => 'Required for all students.'],
                    ['icon' => 'id-card', 'title' => 'Aadhaar Card', 'text' => 'Optional but recommended for verification.'],
                    ['icon' => 'camera', 'title' => "Child's Photo", 'text' => 'Recent passport-size JPEG or PNG photo.'],
                    ['icon' => 'school', 'title' => 'Previous Marksheet', 'text' => 'For Class 2 and above.'],
                ],
                'faq_badge' => 'FAQ',
                'faq_heading' => 'Frequently Asked Questions',
                'faqs' => [
                    ['question' => 'When do admissions open?', 'answer' => 'Admissions open in January for the upcoming academic year.'],
                    ['question' => 'Is there an entrance test?', 'answer' => 'Yes, depending on the class and seat availability.'],
                    ['question' => 'Can I visit the school before applying?', 'answer' => 'Yes, school tours are available on working days.'],
                    ['question' => 'Is there a hostel facility?', 'answer' => 'Yes, separate hostels are available for boys and girls.'],
                    ['question' => 'Are scholarships available?', 'answer' => 'Yes, merit-based scholarships are available.'],
                ],
                'cta_heading' => 'Ready to Apply?',
                'cta_text' => "Register on the Parent Portal and start your child's admission in minutes.",
                'cta_button' => 'Admission',
                'cta_link' => 'parent/register.php',
            ],
        ],
        'campus-life' => [
            'label' => 'Campus Life',
            'title' => 'Campus Life',
            'data' => [
                'hero_title' => 'Life at SIBA Campus',
                'hero_text' => 'A vibrant 12-acre campus built for learning, growing, and thriving.',
                'infra_badge' => 'Infrastructure',
                'infra_heading' => 'World-Class Facilities',
                'infra_text' => 'Every space on our campus is designed to inspire and support student excellence.',
                'infrastructure' => [
                    ['icon' => 'flask', 'title' => 'Science Laboratories', 'text' => 'Modern Physics, Chemistry, Biology, and Computer labs.'],
                    ['icon' => 'book-open', 'title' => 'Central Library', 'text' => 'Extensive volumes, e-journals, and quiet reading spaces.'],
                    ['icon' => 'chalkboard-teacher', 'title' => 'Smart Classrooms', 'text' => 'Interactive classrooms with digital boards and Wi-Fi.'],
                    ['icon' => 'swimming-pool', 'title' => 'Sports Complex', 'text' => 'Pool, courts, grounds, and athletics facilities.'],
                    ['icon' => 'utensils', 'title' => 'Cafeteria & Canteen', 'text' => 'Hygienic and nutritionist-approved meals.'],
                    ['icon' => 'bus', 'title' => 'Transport', 'text' => 'GPS-tracked buses covering major routes.'],
                ],
                'hostel_badge' => 'Residential Life',
                'hostel_heading' => 'A Home Away from Home',
                'hostel_image' => 'https://images.unsplash.com/photo-1555854877-bab0e564b8d5?auto=format&fit=crop&q=80&w=800',
                'hostel_text' => 'Our separate boys and girls hostels provide a safe, structured, and nurturing environment.',
                'hostel_points' => [
                    ['icon' => 'bed', 'title' => 'Comfortable Accommodation', 'text' => 'Spacious rooms and essential amenities.'],
                    ['icon' => 'shield-alt', 'title' => 'Safety & Security', 'text' => 'CCTV surveillance and supervised access.'],
                    ['icon' => 'heart', 'title' => 'Wellness & Health', 'text' => 'Resident nurse and medical support.'],
                ],
                'student_badge' => 'Student Experience',
                'student_heading' => 'More Than Just School',
                'student_text' => "Our campus is alive with events, clubs, and community - there's always something happening.",
                'student_life' => [
                    ['image' => 'https://images.unsplash.com/photo-1541339907198-e08756ebafe3?auto=format&fit=crop&q=80&w=600', 'title' => 'Annual Day & Cultural Fest', 'text' => 'Flagship events showcasing arts and student talent.'],
                    ['image' => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=600', 'title' => 'Inter-School Sports Tournaments', 'text' => 'District and state-level achievements in multiple sports.'],
                    ['image' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600', 'title' => 'Science & Innovation Fair', 'text' => 'Original student research and innovation showcases.'],
                ],
                'cta_heading' => 'Come See It for Yourself',
                'cta_text' => 'Schedule a campus tour and experience SIBA first-hand.',
                'cta_primary_text' => 'Schedule a Tour',
                'cta_primary_link' => 'contact.php',
                'cta_secondary_text' => 'Admission',
                'cta_secondary_link' => 'parent/register.php',
            ],
        ],
        'events' => [
            'label' => 'Events & News',
            'title' => 'Events & News',
            'data' => [
                'hero_title' => 'Events & Latest News',
                'hero_text' => 'Stay updated with the latest happenings at SIBA Public School.',
                'events_badge' => 'Calendar',
                'events_heading' => 'Upcoming Events',
                'events' => [],
                'news_badge' => 'News',
                'news_heading' => 'Latest from SIBA',
                'news' => [
                    ['image' => 'https://images.unsplash.com/photo-1509062522246-3755977927d7?auto=format&fit=crop&q=80&w=600', 'category' => 'Achievement', 'title' => 'SIBA Wins State Basketball Championship', 'text' => "Our U-17 boys' basketball team won the state trophy for the third year.", 'date' => 'March 20, 2026'],
                    ['image' => 'https://images.unsplash.com/photo-1580582932707-520aed937b7b?auto=format&fit=crop&q=80&w=600', 'category' => 'Academic', 'title' => 'Students Excel in Maths Olympiad', 'text' => 'Five students qualified for the national round with medal wins.', 'date' => 'March 10, 2026'],
                    ['image' => 'https://images.unsplash.com/photo-1497633762265-9d179a990aa6?auto=format&fit=crop&q=80&w=600', 'category' => 'Infrastructure', 'title' => 'New Digital Library Wing Inaugurated', 'text' => 'Expanded digital library with e-books and research pods is now open.', 'date' => 'February 28, 2026'],
                ],
            ],
        ],
        'contact' => [
            'label' => 'Contact',
            'title' => 'Contact Us',
            'data' => [
                'hero_title' => 'Get in Touch',
                'hero_text' => "We'd love to hear from you. Reach us anytime through the channels below.",
                'details_badge' => 'Contact Details',
                'details_heading' => 'School Office',
                'contacts' => [
                    ['icon' => 'map-marker-alt', 'title' => 'Address', 'value' => 'Bangaljhi, West Bengal 741123, India'],
                    ['icon' => 'phone', 'title' => 'Phone', 'value' => '+91-75010119960 (Reception)\n+91 98765 43210 (Admissions Cell)'],
                    ['icon' => 'envelope', 'title' => 'Email', 'value' => "info@sibapublicschool.com\nadmissions@sibapublicschool.com"],
                    ['icon' => 'clock', 'title' => 'Office Hours', 'value' => "Mon – Fri: 7 am – 3 pm\nSat: 7 am – 1 pm"],
                ],
                'portal_title' => 'Parent Portal',
                'portal_text' => 'For admission tracking, fee payment, and updates, log in to the Parent Portal.',
                'portal_button_text' => 'Parent Login',
                'portal_button_link' => 'parent/login.php',
                'form_heading' => 'Send Us an Enquiry',
                'form_topics' => [
                    'Admission Inquiry',
                    'Fee Related',
                    'Hostel & Transport',
                    'Academic Information',
                    'Other',
                ],
                'form_footer' => 'We typically respond within 1 business day.',
                'map_title' => 'Interactive map coming soon',
                'map_subtitle' => 'Bangaljhi, West Bengal 741123',
            ],
        ],
    ];
}
